version: "3"

services: 
  nodejs:
    image: milan090/xbot:latest
    container_name: nodejs
    restart: unless-stopped
    environment: 
      - DISCORD_API_KEY=$DISCORD_API_KEY
      - MONGO_URI=$MONGO_URI
    links: 
      - mongo
  mongo:
    image: mongo:3-xenial
    container_name: mongo
    restart: unless-stopped
    environment: 
      - MONGO_URI=$MONGO_URI
    volumes: 
      - ./dbdata:/data/db
